### ISSUE TITLE
Solve CORS problem

### ISSUE THREAD

**Issue by Jefferson227** [Jefferson227/busca-cinema#5]
Well this has been a challenge for me since I couldn't find the solution so far. As you can see in the live demo link, the movies are not loaded due to the CORS problem. It's works okay on localhost because I'm using a proxy configuration in the `ionic.config.json` but when I do a deploy on firebase or remove the proxy configuration it throws that famous message.

So it's been a challenge to make this work on firebase.

`Failed to load https://api-content.ingresso.com/v0/events/city/36/partnership/0: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://find-cinema.firebaseapp.com' is therefore not allowed access.`

**Comment by campionfellin** [comment]
Hey @Jefferson227 have you tried using the CORS library with Express? https://github.com/expressjs/cors

**Comment by p-mayank** [comment]
Have you tried changing the static url as mentioned here : https://stackoverflow.com/questions/38357699/ionic-probleme-no-access-control-allow-origin?

**Comment by Jefferson227** [comment]
@campionfellin actually not, I’ve seeing some solutions using express but in fact I didn’t try anything so far. I’ll take a look closer on your suggestions.

**Comment by Jefferson227** [comment]
@p-mayank I’m currently using the proxy configuration on localhost and it works like a charm, but unfortunately I can’t take this configuration to firebase.

**Comment by campionfellin** [comment]
@Jefferson227 yeah I've used that before and it's worked for me, if you'd like I can work it into this repo later this afternoon.

**Comment by Jefferson227** [comment]
@campionfellin for this I'm working on this other repo https://github.com/Jefferson227/busca-cinema-backend I'm doing some commits there to learn about express.

**Comment by campionfellin** [comment]
@Jefferson227 Awesome! Let me know if you need any help!

**Comment by Jefferson227** [comment]
@campionfellin I've just made a small test on my other repo and right now I'm bypassing the API calls through an application in node/express installing the `cors` package as you suggested. I've deployed this repo on heroku and now I'm able to make the API calls on busca-cinema app without any cors errors.

Thank you very much for your suggestion :smile:
